### ISSUE TITLE
Ingest not possible "file status unknown"

### ISSUE THREAD

**Issue by mindandvision** [jaskie/PlayoutAutomation#25]
Hi ,

first of all - thank you for making this fantastic program available on Github!!

Great work so far.

I have a problem on one machine regarding the ingest of files.
I specified an ingest folder and copied some files into it. I can see these files in the TVPlay media tab. But the file status is always "unknown" - so I'm not able to import those clips.

Any idea?

Thanks

Andreas

**Comment by jaskie** [comment]
It may be caused by absence of MSVC [runtime](https://github.com/jaskie/PlayoutAutomation/wiki/2.-Installation#visual-c-redistributable-for-visual-studio-2015) on the machine.
To get more details: TVPlay uses FFMpeg to verify a media file. TVPlay has its wrapper for FFMpeg's dll's: TAS.FFMpegUtils.dll - a C++ project that requires the runtime library.
To find other reasons, it would be useful to read log files in `logs` directory. Log configuration is in NLog.config file, it would be necessary to change logs verbosity level.

**Comment by mindandvision** [comment]
Hi Jerzy,

thank you very much for taking the time to answer and to help me with this problem. Indeed i set up another machine two days ago for testing where everything ran smoothly.

On the "problem" machine it didn't work right from the start. I reinstalled VC2015 before I installed TVPlay. So this should be OK. Should I deinstall VC2015 and reinstall?

I will check for the LOG Files and send the results.

Cheers

Andreas

**Comment by mindandvision** [comment]
I don't know if that is too much, but do you mind having a look over my system via Teamviewer?

The thing is - I tried to setup another testsystem and TVPlay worked right away without problems. Only on the production system I get the problem that I wrote above.

Thanks for all your effort!

Andreas

**Comment by jaskie** [comment]
@mindandvision, did you get succeed? 
Another reason that came to my mind is Windows 32-bit version, which would generally work, but with this particular problem that you described.
About Teamviewer: It's strictly banned in my company, however I may look at your installation from home (off-hours CET). For this, write a private mail to me.
Kind regards, 
Jurek
