### ISSUE TITLE
Ingest issue

### ISSUE THREAD

**Issue by Nikoxx99** [jaskie/PlayoutAutomation#34]
There is a video.
https://www.dropbox.com/s/j3n56zl4lfjzme4/2017-12-13_08-53-59.mp4?dl=0

The clips show as "Unknown" when i want ingest them to the media folder.
Media folder are the same in TVPlay and CCG, FPS are the same, format are the same.
First is an remote PC where ingest doesn't work, and in my locally pc works perfectlly.

**Comment by jaskie** [comment]
The files should be ingested via previously defined ingest directory, otherwise they must be verified (using small button next to Media Status) manually. Are they?

**Comment by Nikoxx99** [comment]
![2017-12-13_10-41-01](https://user-images.githubusercontent.com/8411262/33947370-37506e1c-dff2-11e7-9636-b333271051da.gif)
Still not working

**Comment by jaskie** [comment]
It seems that FFmpeg wrapper is not working at all (it may be indicated in log file).
Did you installed [VC2105 redistribuable](https://www.microsoft.com/en-us/download/details.aspx?id=53587)?
Rule is: in server folders clips are checked after ingest or when requested; in ingest folders - when clicked.
Excellent movie...

**Comment by Nikoxx99** [comment]
I have installed VC2015, i can try reinstall it and Klite Codec pack, the problem is i can't restart the PC without take us out of the air, i try very early in moorning and tell you.

**Comment by Nikoxx99** [comment]
Ok, it workd but, i found another problem.
When i add a clip to Media folder, it doesn't load until i restart the program, what is a problem.
![2017-12-19_11-58-48](https://user-images.githubusercontent.com/8411262/34169074-319dc214-e4b4-11e7-8ac8-9432a16907f4.gif)

**Comment by jaskie** [comment]
It's "by design". You shouldn't add files to media folder directly, they need to be added through an ingest folder. This way of operation may help to ensure that file is properly encoded and also helps to have consistent files format in server's media folder.
If you have to copy files directly to server media folder, you should also verify such file using "check now" small button in media properties section next to "Media status" (on your movie it's hidden by preview control). Such a verification is also done automatically on app startup, so after app restart it's OK. After this verification file is copied to backup server's media folder (if configured).
