### ISSUE TITLE
Problems compile from source

### ISSUE THREAD

**Issue by brambox** [jaskie/PlayoutAutomation#43]
Hello.
I'm trying to compile from source on windows 10 / vs 2017 but there are a lot of errors going in.
On master it can never compile.
While on developer one was able to finish and i can start program and config but then no files are shown on media folders. There usually is only 1 animation template with id 000000... and that is it.
Any help welcome. 

Thank you!

**Comment by brambox** [comment]
Hello i believe the  no media file listed on developer build  is may be a bug or something.

While i was unable to compile from master i  still used the code from there and the old directory listing on v1.3c and now all files lists fine.

**Comment by jaskie** [comment]
Indeed,
master branch was hard to compile because of its submodule (websocket-sharp). I recently replaced the websocket with tcp socket, and removed the dependency, what behaves much better and it's easier to compile. And just updated the branch to relevant commit, so you may easily build it.
On the other hand, develop branch is now in unstable state - commits beginning with WIP (work in progress) contains unfinished work.
