### ISSUE TITLE
Rundown

### ISSUE THREAD

**Issue by sfahadshahzad** [jaskie/PlayoutAutomation#6]
I am currently testing the TVPlay; When i add some clips in rundown it perfectly play all clips but in case if i close the tvplay application then the clip which is currently playing in the rundown plays till end of the last frame instead of play next clip in rundown. is there any possibility that casparcg play all scheduled  clips in the rundown.
when we reopen the tvplay application it will never show current playing counter if it is possible so i dont need to jump on the next clip and it will automatically continue the rundown.

Thanks and regards

Fahad,

**Comment by yapus** [comment]
There's not "playlsit" inside CasparCG. The only thing you can achieve it putting one next clip to background layer with LOADBG AUTO command, so it will start playing automatically when the current clip's last frame is reached. You can say there's a "playlist" of maximum length of 2 clips within CasparCG. So when you close automation program – it certainly will NOT go on executing your rundown.

**Comment by jaskie** [comment]
As a supplement: It's planned to split this (I mean TVPlay.exe) into two parts:
- scheduling engine and media manager, that could run as a service,
- user interface, client application that could be opened and closed as needed.

First approach to introduce this model (client-server) is TVPlayMedia.exe application, which allows to remotely manage media (media tab for a channel in TVPlay.exe). Due to its early development stage, it's not included in binary release.

Second note: In next binary release, TVPlay.exe will contain a feature that if you restart the application **before** currently playing clip ends, it will continue executing rundown (assuming that nothing else were played on the channel during restart).

**Comment by sfahadshahzad** [comment]
Many thanks for considering my opinion; can you please tell me how can i setup redundant setup for each channel,

Let say if i have two casparcg servers and i create different playout servers in config and create one rundown for both configured playout servers.
when i play video on first server it will automatically play on other server. 
media files automaticall copied on both playout servers when i add some clips in rundown.

Regards,

Fahad Shehzad

**Comment by jaskie** [comment]
Hi,
i've just published this [wiki](https://github.com/jaskie/PlayoutAutomation/wiki/4.-Redundancy) page.
Kind regards, 
Jurek

**Comment by sfahadshahzad** [comment]
Thank you very much for considering my request; i Just saw the wiki page very well described.

 Regards,

Fahad

**Comment by jaskie** [comment]
There are also new binaries available.

**Comment by sfahadshahzad** [comment]
Is there any possibility of calendar type preview pane on left side for rundown; like if i need to make a rundown in advance and save or export / import playlist.
I just saw changes regarding Animated Media ? what does it mean and how can i use AnimatedMedia ?

Thanks

**Comment by jaskie** [comment]
Calendar is not planned as rundowns can be grouped in containers (which are able to hide), so rundowns can be made in advance, too.
AnimantedMedia are to support Caspar Flash/html template graphics. They are not operational yet (I plan to do it this week).
Kind regards,
Jurek
