### ISSUE TITLE
Doubts in the configuration

### ISSUE THREAD

**Issue by theusmpa** [jaskie/PlayoutAutomation#77]
Hello, good afternoon!

I have some doubts that were not clear to me during the setup process:

1) What is the purpose of the configuration: "Instance Connection"?

![Intance binding](https://user-images.githubusercontent.com/6371447/85172769-2072b800-b248-11ea-8fec-5cafd0ccedf3.jpg)

2) What is the purpose of the configuration: name of the "active device" and "URL of the view", could you give me an example of valid parameters to be placed in these fields?

![live device](https://user-images.githubusercontent.com/6371447/85172788-2799c600-b248-11ea-864e-9ddd2e497234.jpg)

3) Finally, what is the purpose of this configuration?

![on slow link](https://user-images.githubusercontent.com/6371447/85172799-2c5e7a00-b248-11ea-832f-8a4b11ce9771.jpg)

Thank you and apologize for not understanding!

Matheus

**Comment by jaskie** [comment]
Definitely, good documentation is missing, I know.
So:
1. You can set instance binding number on _Config file and database_ settings, as well on rundown engine configuration. When TVPlay (or TVPlaySvc) starts, it will only load from database engines that have the same number in local settings (engine instance = config file instance). This makes sense only for MySql installations, and allows to have several installations connected to the same database. However, it's nearly useless, and I'll probably replace this with "is enabled" setting for engine, as disabling configured engine is it's only real purpose.
2. Live device name: it is CasparCG source name that will be loaded when "live" starts on rundown. In practice it is `DECKLINK N` (where N - card number) or `route://N` (where N is channel number on which live stream is playing perpetually).
3. Preview URL: on recording tab, when you select channel for record, it's possible to preview it in NDI preview plugin. The syntax is `ndi://COMPUTER_NAME:SOURCE_NAME`
4. On slow link (WAN connection) also will be removed, because _Directory kind: Simple, not watched folder_ was introduced, and it seems to be redundant.

**Comment by theusmpa** [comment]
Very good! I understand perfectly!

Thank you, great app.
